#pragma once

#include <cstdint>

#include "mercury/core/types.hpp"

namespace mercury {

// Represents a completed transaction between a buyer and seller.
// Generated by the MatchingEngine when two orders are compatible.
// The execution price is always the resting (passive) order's price —
// the aggressive (incoming) order accepts whatever the passive order offered.
struct Trade {
    OrderId  buy_order_id{};
    OrderId  sell_order_id{};
    Price    price{};     // Resting order's price — not the aggressive order's limit.
    Quantity quantity{};  // Amount exchanged in this trade.
    uint64_t timestamp{}; // Nanoseconds since epoch at time of execution.
};

}  // namespace mercury
